import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { expect, it } from 'vitest'

const readme = readFileSync(resolve(process.cwd(), 'README.md'), 'utf8')

it('documents hosted deployment in migration-before-function order', () => {
  const login = readme.indexOf('npx supabase login')
  const link = readme.indexOf('npx supabase link --project-ref kwoppqigrtvgmmbnzbpx')
  const push = readme.indexOf('npx supabase db push')
  const secrets = readme.indexOf('npx supabase secrets set SUBTITLE_PERSONAL_TOKEN=<random-secret>')
  const deploy = readme.indexOf('npx supabase functions deploy ingest-subtitles --no-verify-jwt')

  expect(login).toBeGreaterThan(-1)
  expect(link).toBeGreaterThan(login)
  expect(push).toBeGreaterThan(link)
  expect(secrets).toBeGreaterThan(push)
  expect(deploy).toBeGreaterThan(secrets)
  expect(readme).toContain('npx supabase migration list')
  expect(readme).toContain('npx supabase db lint --linked --level warning')
  expect(readme).toContain('Remote deployment compilation is mandatory')
})

it('documents the server-side movie quote montage example', () => {
  expect(readme).toContain('npx supabase functions deploy movie-quote-montage --no-verify-jwt')
  expect(readme).toContain("'x-subtitle-token' = $env:SUBTITLE_PERSONAL_TOKEN")
  expect(readme).toContain('"theme":"love and time"')
  expect(readme).toContain('"quoteCount":8')
  expect(readme).toContain('"matchThreshold":0.72')
  expect(readme).toContain('"maxPerMovie":1')
  expect(readme).toContain("new Supabase.ai.Session('gte-small')")
})

it('documents the isolated Supabase RRF experiment', () => {
  expect(readme).toContain('npx supabase functions deploy hybrid-subtitle-search --no-verify-jwt')
  expect(readme).toContain('/functions/v1/hybrid-subtitle-search')
  expect(readme).toContain('"query":"love and time","limit":12')
  expect(readme).toContain('rrfScore')
  expect(readme).toContain('semanticRank')
  expect(readme).toContain('fullTextRank')
  expect(readme).toContain('full_text_weight = 1')
  expect(readme).toContain('semantic_weight = 2')
  expect(readme).toContain('rrf_k = 50')
})

it('documents the private Vecteezy video candidate workflow without subtitle examples', () => {
  expect(readme).toContain('VECTEEZY_ACCOUNT=<account-id>')
  expect(readme).toContain('VECTEEZY_API_KEY=<api-key>')
  expect(readme).toContain('AI_INFERENCE_API_HOST=https://<authenticated-ollama-gateway>')
  expect(readme).toContain('OLLAMA_MODEL=gemma4:12b')
  expect(readme).toContain('VIDEO_PLANNER_TRANSPORT=supabase-ai')
  expect(readme).toContain('OLLAMA_GATEWAY_SECURITY_CONFIRMED=true')
  expect(readme).toContain('VIDEO_PLANNER_TRANSPORT=ollama-http')
  expect(readme).toContain('OLLAMA_AUTH_TOKEN=<bearer-token>')
  expect(readme).toContain('unauthenticated `GET /api/tags` must return HTTP 401 or 403')

  const push = readme.indexOf('npx supabase db push')
  const seed = readme.indexOf('npx supabase functions deploy seed-visual-concepts --no-verify-jwt')
  const match = readme.indexOf('npx supabase functions deploy match-video-assets --no-verify-jwt')
  const select = readme.indexOf('npx supabase functions deploy select-video-asset --no-verify-jwt')
  expect(seed).toBeGreaterThan(push)
  expect(match).toBeGreaterThan(seed)
  expect(select).toBeGreaterThan(match)

  expect(readme).toContain("'x-subtitle-token' = $env:SUBTITLE_PERSONAL_TOKEN")
  expect(readme).toContain('"theme":"a fresh start after uncertainty"')
  expect(readme).toContain('"candidateCount":8')
  expect(readme).toContain('inclusive range 5-10')
  expect(readme).toContain('`literal`, `action`, and `metaphor`')
  expect(readme).toContain('manual selection')
  expect(readme).toContain('`video_search_runs`')
  expect(readme).toContain('`video_search_queries`')
  expect(readme).toContain('`video_search_candidates`')
  expect(readme).toContain('`video_asset_selections`')
  expect(readme).toContain('idempotent')
  expect(readme).toContain('does not call a Vecteezy download endpoint')
  expect(readme).toContain('does not fetch media')
  expect(readme).toContain('does not train')
  expect(readme).toContain('Rollback and deactivation')
})
